# Generated by Django 4.0.3 on 2022-08-12 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sandbox', '0002_user_alter_sandbox_body_alter_sandbox_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sandbox',
            name='body',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='sandbox',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='sandbox',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
